[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$version"
version_scheme = "semver2"
version = "0.1.0"
version_files = [
    "Sources/WC/PackageMetadata.swift:version",
]
major_version_zero = true
